# Copyright 2020 Google, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: SSH and Update to Google Compute Engine

on:
  push:
    branches:
    - deploy/**

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  BASTION_IP: ${{ secrets.FIELDMAN_TEST_BASTION_IP }}
  GCE_INSTANCE: josel-staging        # TODO: update to instance name
  GCE_INSTANCE_ZONE: asia-east1-b    # TODO: update to instance zone

jobs:
  setup-ssh-update-deploy:
    name: Setup, SSH, Update, and Deploy
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '286.0.0'
        service_account_email: ${{ secrets.GCE_SA_EMAIL }}
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: ${{ secrets.GCE_PROJECT }}

    # Update GCP firewall
    - name: Allowing github ip to GCP firewall
      run: |-
        export TEMP_IP=$(dig +short myip.opendns.com @resolver1.opendns.com)
        export SOURCES=$(gcloud compute firewall-rules describe josel-staging-allow-github --format="table(sourceRanges.list())")
        echo $TEMP_IP
        echo $SOURCES
        gcloud compute firewall-rules update josel-staging-allow-github --source-ranges $BASTION_IP,$TEMP_IP
        gcloud compute firewall-rules update josel-staging-allow-github --no-disabled

    # SSH to machinge
    - name: Update machine from repository
      env:
        token: ${{ secrets.NAVAGISJOSEL_TOKEN }}
        s_command: |-
          ls -al &&
          sudo su &&
          cd /opt/fieldman/osa/briar-osa &&
          ls -al &&
          sudo chmod 777 -R /opt/fieldman/osa/briar-osa/* &&
          sudo rm -rf .git/index.lock &&
          sudo git reset --hard HEAD &&
          echo "Updating to branch ${GITHUB_REF##*/}" &&
          sudo git fetch https://navagisjosel:$token@github.com/Navagis-LLC/briar-osa.git ${GITHUB_REF##*/} &&
          sudo git checkout ${GITHUB_REF##*/} &&
          sudo git pull https://navagisjosel:$token@github.com/Navagis-LLC/briar-osa.git ${GITHUB_REF##*/} &&
          sudo source ./venv/bin/activate &&
          sudo pip install --upgrade pip &&
          sudo pip install -r requirements.txt &&
          ls -al
      run: |-
        gcloud compute ssh --project $PROJECT_ID --zone $GCE_INSTANCE_ZONE $GCE_INSTANCE -- $s_command
        pwd
        ls -al

    - name: Sleep
      uses: jakejarvis/wait-action@master
      with:
        time: '60s'

    # Failure handler
    - name: The custom job cleanup always
      if: always()
      run: |-
        gcloud compute firewall-rules update josel-staging-allow-github --source-ranges $BASTION_IP
        gcloud compute firewall-rules update josel-staging-allow-github --disabled
